spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

app:
  mode: TEST